Chakraborty Model
ECSIM/opem pull request #149
Opened 2021-03-01 23:18 UTC by sepandhaghighi

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.
- Chakraborty dynamic model added

#### Any other comments?

2021-03-10 00:57 UTC, sepandhaghighi commented
@sadrasabouri @sarminh @kasraaskari
Please review this PR ;-)

Document Link : https://nbviewer.jupyter.org/github/ECSIM/opem/blob/chakraborty1/Documents/Chakraborty.ipynb
EXE Link : https://www.dropbox.com/s/ed0q76ysbdnlp20/OPEM_PR_Chakraborty.exe?dl=0

2021-03-11 15:55 UTC, kasraaskari approved these changes

2021-03-13 20:00 UTC, sadrasabouri requested changes
Minor edits may be needed.
Also the number of newlines between each function is not identical in `Chakraborty.py`, it may be needed to be fixed.

2021-03-13 20:00 UTC, sadrasabouri commented on opem/Dynamic/Chakraborty.py
> +    :return: Nernst gain [V} as float
shouldn't be `[v]` or `{v}`?

2021-03-13 20:00 UTC, sadrasabouri commented on opem/Dynamic/Chakraborty.py
> +    :type N0 : int
Despite `N0` here, we have`N` in arguments.

2021-03-13 20:00 UTC, sadrasabouri commented on opem/Dynamic/Chakraborty.py
> +        print("[Error] " +Simulation_Title +" Simulation Failed!(Check Your Inputs)")
Spaces are not well-formed in this line.

2021-03-14 18:28 UTC, sarminh approved these changes
All changes are approved.

2021-03-15 21:52 UTC, sepandhaghighi commented on opem/Dynamic/Chakraborty.py
> +    :return: Nernst gain [V} as float
fixed in https://github.com/ECSIM/opem/pull/149/commits/85442649ec3014cd4951649eab558bc36b492b15

2021-03-15 21:52 UTC, sepandhaghighi commented on opem/Dynamic/Chakraborty.py
> +    :type N0 : int
fixed in https://github.com/ECSIM/opem/pull/149/commits/fa88049c82fe84f33ba1b0cc5b36b48bc32dbc7a

2021-03-15 21:53 UTC, sepandhaghighi commented on opem/Dynamic/Chakraborty.py
> +        print("[Error] " +Simulation_Title +" Simulation Failed!(Check Your Inputs)")
fixed in https://github.com/ECSIM/opem/pull/149/commits/f11754fe594f52e04df770562c29229e311a5ed2

2021-03-17 06:03 UTC, sadrasabouri approved these changes
LGTM

2021-03-17 06:03 UTC, merged