Folder
ECSIM/opem pull request #199
Opened 2023-10-27 20:03 UTC by sepandhaghighi

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2023-11-07 06:03 UTC, sadrasabouri requested changes

2023-11-07 06:03 UTC, sadrasabouri commented on opem/Functions.py
> +        os.mkdir(sim_folder)
What is this for?

2023-11-07 06:03 UTC, sadrasabouri commented on opem/Functions.py
> +        os.mkdir(sim_folder)
similar here.

2023-11-07 06:03 UTC, sadrasabouri commented on opem/Functions.py
> +        os.mkdir(sim_folder)
and here.

2023-11-07 07:28 UTC, sepandhaghighi commented on opem/Functions.py
> +        os.mkdir(sim_folder)
fixed in https://github.com/ECSIM/opem/pull/199/commits/4745d34ee7569d541ff815ae9ca334291fcb18fc

2023-11-07 07:28 UTC, sepandhaghighi commented on opem/Functions.py
> +        os.mkdir(sim_folder)
fixed in https://github.com/ECSIM/opem/pull/199/commits/4745d34ee7569d541ff815ae9ca334291fcb18fc

2023-11-07 07:28 UTC, sepandhaghighi commented on opem/Functions.py
> +        os.mkdir(sim_folder)
fixed in https://github.com/ECSIM/opem/pull/199/commits/4745d34ee7569d541ff815ae9ca334291fcb18fc

2023-11-07 07:28 UTC, sepandhaghighi commented on opem/Functions.py
> +        os.mkdir(Folder)
fixed in https://github.com/ECSIM/opem/pull/199/commits/4745d34ee7569d541ff815ae9ca334291fcb18fc

2023-11-09 06:30 UTC, sadrasabouri approved these changes

2023-11-09 06:30 UTC, merged