Notebook scripts
ECSIM/opem pull request #206
Opened 2023-12-14 18:21 UTC by sepandhaghighi

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.
- `notebook_to_html.py` script added
- `notebook_check.py` renamed to `notebook_run.py`
- Test system modified
- Documents modified

#### Any other comments?

2023-12-15 07:48 UTC, sadrasabouri requested changes

2023-12-15 07:48 UTC, sadrasabouri commented on CHANGELOG.md
>  - License updated
- `notebook_check.py` script renamed to `notebook_run.py`

2023-12-15 07:48 UTC, sadrasabouri commented on otherfile/version_check.py
> +    "OPEM.spec": SPEC_ITEMS}
It's better to have `key: val` in each line.

2023-12-18 09:29 UTC, sepandhaghighi commented on otherfile/version_check.py
> +    "OPEM.spec": SPEC_ITEMS}
fixed in https://github.com/ECSIM/opem/pull/206/commits/3e5fe63632ad9a2a4655300bacb1e32f3c4960bc

2023-12-18 09:30 UTC, sepandhaghighi commented on CHANGELOG.md
>  - License updated
fixed in https://github.com/ECSIM/opem/pull/206/commits/4dcf47313a8bd944e0f9abe3cc259e8d62849f39

2023-12-19 16:34 UTC, sadrasabouri approved these changes
Good job

2023-12-19 16:35 UTC, merged